name: Build Go program for all platforms

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.22.2'
    - run: go version

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o ./internal/play/play-linux ./internal/play

    - name: Build for macOS
      run: GOOS=darwin GOARCH=amd64 go build -o ./internal/play/play-darwin ./internal/play

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o ./internal/play/play-windows.exe ./internal/play

    - name: Archive builds
      uses: actions/upload-artifact@v4
      with:
        name: builds
        path: |
          internal/play/play-linux
          internal/play/play-darwin
          internal/play/play-windows.exe

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          internal/play/play-linux
          internal/play/play-darwin
          internal/play/play-windows.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}